import { useState, useEffect, Suspense } from 'react';
import { Text, View, ActivityIndicator } from 'react-native';
import { useFonts } from 'expo-font';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as SplashScreen from 'expo-splash-screen';
import { SQLiteProvider } from 'expo-sqlite';
import * as SQLite from 'expo-sqlite/legacy';

import Home from './components/Home';
import Movies from './components/Movies/Movies';
import Plans from './components/Plans/Plans';
import NewMovie from './components/Movies/NewMovie';
import NewPlan from './components/Plans/NewPlan';
import EditMovie from './components/Movies/EditMovie';
import EditPlan from './components/Plans/EditPlan';

SplashScreen.preventAutoHideAsync();

const Stack = createNativeStackNavigator();

export default function App() {
  const [dbLoaded, setDbLoaded] = useState(false);

  const db = SQLite.openDatabase("chispas.db");

  useEffect(()=> {
    db.transaction((tx) => {
      tx.executeSql("CREATE TABLE IF NOT EXISTS plans (id INTEGER PRIMARY KEY AUTOINCREMENT, plan TEXT NOT NULL, location TEXT NOT NULL, indoor_outdoor TEXT NOT NULL, price FLOAT NOT NULL, eating TEXT NOT NULL, done TEXT NOT NULL)")
    });

    db.transaction((tx) => {
      tx.executeSql("CREATE TABLE IF NOT EXISTS movies (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, type TEXT NOT NULL, duration TEXT NOT NULL, genre TEXT NOT NULL, platform TEXT NOT NULL, status TEXT NOT NULL)")
    });

    db.transaction((tx) => {
      tx.executeSql("SELECT COUNT(*) AS count FROM plans", [], (_, { rows }) => {
        if (rows.item(0).count === 0) { // insert if table is empty
          tx.executeSql(
            `INSERT INTO plans (plan, location, indoor_outdoor, price, eating, done) VALUES 
            ('Açai Amazonia', 'Madrid', 'Indoor', 7, 'Yes', 'Yes'),
            ('Aguarales De Valpalmas', 'Zaragoza', 'Outdoor', 0, 'No', 'No'),
            ('Ajedrez Con Macaggons', 'Madrid', 'Indoor', 0, 'Yes', 'No'),
            ('Alehop', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Altitude Park (15% Carné Joven)', 'Madrid', 'Indoor', 13, 'No', 'No'),
            ('Amazonia', 'Madrid', 'Outdoor', 23, 'No', 'Yes'),
            ('Amorino Corte Inglés', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Animal Crossing', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Aniversario Pista De Patinaje (Hamburguesas Caras)', 'Madrid', 'Indoor', 20, 'Yes', 'Yes'),
            ('Apuntes Detrás De Las Fotos (Beadactilo)', 'Madrid, Talavera', 'Indoor', 0, 'No', 'Yes'),
            ('Aquopolis', 'Madrid', 'Outdoor', 19.99, 'No', 'Yes'),
            ('Aranjuez', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Atoope Park', 'Madrid', 'Indoor', 12, 'No', 'Yes'),
            ('Autocine Madrid', 'Madrid', 'Indoor', 8, 'No', 'No'),
            ('Ávila', 'Ávila', 'Outdoor', 0, 'No', 'Yes'),
            ('Ayllón', 'Segovia', 'Outdoor', 0, 'No', 'No'),
            ('Azotea Cibeles', 'Madrid', 'Outdoor', 3, 'No', 'Yes'),
            ('Baños Romanos De La Hedionda', 'Málaga', 'Outdoor', 0, 'No', 'No'),
            ('Bar Croquetas Tenis', 'Talavera', 'Indoor', 2, 'Yes', 'Yes'),
            ('Bar Montserrat Pulpo', 'Madrid', 'Indoor', 8, 'Yes', 'No'),
            ('Bar Una Grande Libre (Chino Franquista)', 'Madrid', 'Indoor', 0, 'Yes', 'No'),
            ('Barcas Retiro', 'Madrid', 'Outdoor', 6, 'No', 'Yes'),
            ('Belen Del Ayuntamiento Madrid', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Bocadillo El Brillante', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Bolera Parquesur', 'Madrid', 'Indoor', 5, 'No', 'Yes'),
            ('Bolera Sambil', 'Madrid', 'Indoor', 4.5, 'No', 'No'),
            ('Bosque Encantado', 'Madrid', 'Outdoor', 12, 'No', 'No'),
            ('Bricks Madrid Gran Vía', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Bubble Tea Pio', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Bubbletea Madrid', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Buitrago Del Lozoya', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Caixaforum: Patagonia', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Caixaforum: Pixar', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Caja De Macarons', 'Madrid', 'Indoor', 10, 'Yes', 'No'),
            ('Callejón Madriagón (X Madrid)', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Caminito Del Rey', 'Málaga', 'Outdoor', 10, 'No', 'No'),
            ('Camino De Hierro (Parque Natural De Las Arribes Del Duero)', 'Salamanca', 'Outdoor', 0, 'No', 'No'),
            ('Camiseta Aniversario (Collage)', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Campo De Criptana/Consuegra (Molinos)', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('Cañon Del Rio Lozoya', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Caramelos Paco', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Casa Del Libro', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Casa Mira', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Casa Museo Del Ratoncito Pérez', 'Madrid', 'Indoor', 7, 'No', 'No'),
            ('Central Hidroeléctrica', 'Talavera', 'Indoor', 0, 'No', 'No'),
            ('Ceramica En Talavera', 'Talavera', 'Indoor', 0, 'No', 'No'),
            ('Chinchón', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Chun Li', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Churros En Chocolatería San Ginés', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Círculo De Bellas Artes', 'Madrid', 'Outdoor', 10, 'No', 'No'),
            ('Croquetas Sol', 'Madrid', 'Indoor', 4, 'Yes', 'No'),
            ('Cuenca - Tirolina Más Larga De Europa', 'Cuenca', 'Outdoor', 25, 'No', 'No'),
            ('Cueva De Las Palomas', 'Valencia', 'Outdoor', 0, 'No', 'No'),
            ('Dardos', 'Talavera', 'Indoor', 1, 'No', 'Yes'),
            ('Disneyland London 2024 / 2029', 'London', 'Outdoor', 80, 'No', 'No'),
            ('Doña Manolita', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Dorayakis Madrid', 'Madrid', 'Indoor', 2.5, 'Yes', 'Yes'),
            ('Duck Store Madrid', 'Madrid', 'Indoor', 10, 'No', 'Yes'),
            ('El Descenso Del Sella', 'Asturias', 'Outdoor', 16, 'No', 'No'),
            ('El Escorial', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('El Esquinazo (Tostas Gigantes)', 'Madrid', 'Indoor', 10, 'Yes', 'No'),
            ('El Faro Del Caballo', 'Cantabria', 'Outdoor', 0, 'No', 'No'),
            ('El Hachazo (3 Opciones)', 'Madrid', 'Indoor', 14, 'No', 'No'),
            ('El Hormiguero', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('El Parrizal', 'Teruel', 'Outdoor', 0, 'No', 'No'),
            ('El Prado Talavera', 'Talavera', 'Outdoor', 0, 'No', 'Yes'),
            ('Embalse De Bolarque', 'Guadalajara', 'Outdoor', 0, 'No', 'No'),
            ('Embalse De San Juan Kayaks', 'Madrid', 'Outdoor', 9, 'No', 'No'),
            ('En Busca Del Tiempo (Vasco)', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Espacio Iberia Callao', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Estación Gran Vía', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Exposicion Telefonica Madrid', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Filipinos', 'Madrid', 'Indoor', 1.5, 'Yes', 'Yes'),
            ('Filipo Pizza', 'Madrid', 'Indoor', 15, 'Yes', 'No'),
            ('Fitur', 'Madrid', 'Indoor', 13.20, 'No', 'Yes'),
            ('Flechas Primark', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Fotomaton Faunia', 'Madrid', 'Outdoor', 3, 'No', 'Yes'),
            ('Friendship Bracelets', 'Talavera', 'Indoor', 2, 'No', 'Yes'),
            ('Frigopie', 'Talavera', 'Indoor', 2, 'Yes', 'Yes'),
            ('Fuente De Los Baños', 'Castellón', 'Outdoor', 0, 'No', 'No'),
            ('Fuentes De La Granja De San Ildefonso', 'Segovia', 'Outdoor', 4, 'No', 'No'),
            ('Gioelia (Granizado Italiano)', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Guirnalda Ganchillo', 'Madrid', 'Indoor', 2, 'No', 'Yes'),
            ('Hacer Gyozas', 'Madrid, Talavera', 'Indoor', 0, 'Yes', 'No'),
            ('Hacer Sushi', 'Madrid, Talavera', 'Indoor', 0, 'Yes', 'No'),
            ('Hacer Udon', 'Madrid, Talavera', 'Indoor', 0, 'Yes', 'No'),
            ('Heladeria Rocambolesc', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Helado Gallego Calle Arenal', 'Madrid', 'Indoor', 3, 'Yes', 'Yes'),
            ('Hotel Riu Terraza', 'Madrid', 'Outdoor', 10, 'No', 'No'),
            ('Huesca - Tirolina Más Rápida Del Mundo', 'Huesca', 'Outdoor', 44.90, 'No', 'No'),
            ('Ikea', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Ikea (Comida)', 'Madrid', 'Indoor', 10, 'Yes', 'No'),
            ('Jardín Banca March (C/ De Castelló, 75)', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Jardín Botánico De Madrid', 'Madrid', 'Outdoor', 2, 'No', 'Yes'),
            ('Jumplandia', 'Talavera', 'Indoor', 12, 'No', 'No'),
            ('Kaiten Sushi', 'Madrid', 'Indoor', 14.95, 'Yes', 'Yes'),
            ('Karting', 'Madrid, Talavera', 'Outdoor', 20, 'No', 'No'),
            ('Kayak Cazalegas', 'Talavera', 'Outdoor', 22, 'No', 'Yes'),
            ('Kayak Duratón', 'Madrid', 'Outdoor', 16.20, 'No', 'Yes'),
            ('Koi Talavera', 'Talavera', 'Indoor', 8, 'Yes', 'Yes'),
            ('Kuraya', 'Madrid', 'Indoor', 3, 'Yes', 'Yes'),
            ('La Alhambra', 'Granada', 'Indoor', 30, 'No', 'No'),
            ('La Ciudad De Las Artes Y Las Ciencias', 'Valencia', 'Outdoor', 42.70, 'No', 'Yes'),
            ('La Ciudad De Los Niños (Tres Cantos)', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('La Federala', 'Madrid', 'Indoor', 12, 'Yes', 'Yes'),
            ('La Fresería', 'Madrid', 'Outdoor', 5, 'Yes', 'Yes'),
            ('La Mayorquina Menú Degustación', 'Madrid', 'Indoor', 7, 'Yes', 'No'),
            ('La Pedriza', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('La Playa De Madrid', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('La Rosaleda (Retiro)', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('La Ruta De La Jara', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('La Tortilla 2.0', 'Madrid', 'Indoor', 2.5, 'Yes', 'No'),
            ('Laberinto De Peñíscola', 'Castellón', 'Outdoor', 0, 'No', 'No'),
            ('Laberinto Del Parque De Tentegorra', 'Cartagena', 'Outdoor', 0, 'No', 'No'),
            ('Lanzarote', 'Canarias', 'Outdoor', 0, 'No', 'No'),
            ('Las Barrancas de Burujón', 'Toledo', 'Indoor', 0, 'No', 'Yes'),
            ('Las Becerras', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('Las Rozas Village', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Lego Parquesur', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Lenguas De Gato La Mayorquina', 'Madrid', 'Indoor', 2, 'Yes', 'Yes'),
            ('Leones Marinos Faunia', 'Madrid', 'Outdoor', 50.90, 'No', 'Yes'),
            ('Libreria Principe Pio', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Llao Llao', 'Madrid', 'Indoor', 3, 'Yes', 'Yes'),
            ('Macayaki', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Maillard Smash Burguer', 'Madrid', 'Indoor', 6, 'Yes', 'Yes'),
            ('Mananatial De La Salud Del Arroyo, Parque Del Oeste', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Marihuana Bronca Total (Camiseta Green Day)', 'Madrid', 'Indoor', 20, 'No', 'Yes'),
            ('Mascarillas Cara', 'Madrid', 'Indoor', 1, 'No', 'No'),
            ('McQueen', 'Talavera', 'Indoor', 6, 'Yes', 'Yes'),
            ('Medievales Ávila', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Mercado San Miguel', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Mini Golf Las Rozas', 'Madrid', 'Outdoor', 10, 'No', 'No'),
            ('Mistura', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Mobility Museum', 'Zaragoza', 'Indoor', 5, 'No', 'No'),
            ('Mochi Corte Inglés Club Gourmet', 'Madrid', 'Indoor', 4.5, 'Yes', 'Yes'),
            ('Monolitos Talavera', 'Talavera', 'Outdoor', 0, 'No', 'Yes'),
            ('Montaña Artificial Del Retiro', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Moscovitas', 'Madrid', 'Indoor', 19, 'Yes', 'Yes'),
            ('Museo Antropológico', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Arqueológico Nacional', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Chamberí Madrid', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo De Cerámica Ruiz De Luna', 'Talavera', 'Indoor', 0, 'No', 'Yes'),
            ('Museo De Historia Natural De Madrid', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo De La Aviacion De Getafe', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Museo Del Aire Y Del Espacio', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Del Jamón', 'Madrid', 'Indoor', 0, 'Yes', 'Yes'),
            ('Museo Del Prado', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Del Turrón (Madrid)', 'Madrid', 'Indoor', 1.5, 'Yes', 'Yes'),
            ('Museo Etnográfico', 'Talavera', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Geominero', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Museo Naval Madrid', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Reina Sofía', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Museo Trenes Históricos Chamartín', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Mutua Madrid Open', 'Madrid', 'Outdoor', 70, 'No', 'Yes'),
            ('Nacimiento Del Ebro', 'Cantabria', 'Outdoor', 0, 'No', 'No'),
            ('Nerfs', 'Madrid, Talavera', 'Indoor', 0, 'No', 'No'),
            ('Normal Principe Pio', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Nunuka Madrid (Comida Georgiana)', 'Madrid', 'Indoor', 25, 'Yes', 'No'),
            ('Ojo Del Buey', 'Asturias', 'Outdoor', 0, 'No', 'No'),
            ('Outlet Real Madrid', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Padel Talavera', 'Talavera', 'Outdoor', 2.20, 'No', 'Yes'),
            ('Palacio De Cristal', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Palacio De Hielo', 'Madrid', 'Indoor', 12, 'No', 'No'),
            ('Palazzo', 'Madrid', 'Indoor', 3.5, 'Yes', 'Yes'),
            ('Pantalón Ganchillo Thick Fil A', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Parque De Atenas (Flechas)', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Parque De La Quinta De Los Molinos', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Parque De Los Sifones', 'Talavera', 'Outdoor', 0, 'No', 'Yes'),
            ('Parque El Capricho', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Parque Europa', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Parque Natural De Las Bardenas Reales', 'Navarra', 'Outdoor', 0, 'No', 'No'),
            ('Pasaporte Metro (Chamberí)', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Pastelería Pan Feliz', 'Madrid', 'Indoor', 3, 'Yes', 'Yes'),
            ('Patinaje Xmadrid', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Patones De Arriba', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Pepito De Crema La Mallorquina', 'Madrid', 'Indoor', 2, 'Yes', 'Yes'),
            ('Pez Tortilla', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Picnic Río Parque Del Oeste', 'Madrid', 'Outdoor', 0, 'Yes', 'No'),
            ('Piedralaves (Desde Talavera)', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('Piscina Hotel Cool Rooms Palacio De Atocha', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Piscina Puerta De Hierro', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Pista De Hielo Colon / Matadero', 'Madrid', 'Outdoor', 6, 'No', 'No'),
            ('Plane Sightseeing En Barajas', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Planetario', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Plaza Mayor', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Plaza Mayor Bocadillo De Calamares', 'Madrid', 'Indoor', 4, 'Yes', 'Yes'),
            ('Plaza Mayor Mercado Navideño', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Plaza Rio 2', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Poke House', 'Madrid', 'Indoor', 9, 'Yes', 'Yes'),
            ('Pontejos', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Ramen Calle Leganitos', 'Madrid', 'Indoor', 2, 'Yes', 'Yes'),
            ('Ramen Shifu', 'Madrid', 'Indoor', 10, 'Yes', 'Yes'),
            ('Rápidos Rio Tajo', 'Talavera', 'Outdoor', 35, 'No', 'No'),
            ('Rastro', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Real Observatorio De Madrid', 'Madrid', 'Indoor', 4, 'No', 'No'),
            ('Replay Outlet Boardgame Cafe', 'Madrid', 'Indoor', 2, 'No', 'No'),
            ('Réplica Cueva Altamira', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Restaurante A Ri Rang (Buffet Libre Korean Bbq)', 'Madrid', 'Indoor', 21.50, 'Yes', 'No'),
            ('Restaurante Botín (Más Antiguo Del Mundo)', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Revuelto (Sandwiches Coreanos)', 'Madrid', 'Indoor', 7.5, 'Yes', 'Yes'),
            ('Roli Rolls', 'Madrid', 'Indoor', 1.75, 'Yes', 'No'),
            ('Running Sushi in Akihabara', 'Madrid', 'Indoor', 15.99, 'Yes', 'Yes'),
            ('Ruta De Las Cárcavas', 'Madrid, Guadalajara', 'Outdoor', 0, 'No', 'No'),
            ('Ruta De Las Maravillas', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Salt In Cake (Cinnamon Rolls)', 'Madrid', 'Indoor', 3.9, 'Yes', 'Yes'),
            ('Salto De Poveda, Parque Natural Del Alto Tajo', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('Scalextric Tres Aguas', 'Madrid', 'Indoor', 1.5, 'No', 'Yes'),
            ('Segovia', 'Segovia', 'Outdoor', 0, 'No', 'Yes'),
            ('Sepúlveda', 'Segovia', 'Outdoor', 0, 'No', 'No'),
            ('Shangrilla Dimsun Calle Leganitos', 'Madrid', 'Indoor', 10, 'Yes', 'No'),
            ('Show Luces Parque Europa', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Sibuya (Sushi)', 'Madrid', 'Indoor', 12, 'Yes', 'No'),
            ('Sigüenza', 'Guadalajara', 'Outdoor', 0, 'No', 'No'),
            ('Speed Slot Sambil', 'Madrid', 'Indoor', 1.5, 'No', 'No'),
            ('Steven F Udvar-Hazy', 'Washington DC', 'Indoor', 0, 'No', 'No'),
            ('Sufu Cake', 'Madrid', 'Indoor', 5.90, 'Yes', 'Yes'),
            ('Sushi Shan', 'Madrid', 'Indoor', 14, 'Yes', 'No'),
            ('Sushido Talavera', 'Talavera', 'Indoor', 15, 'Yes', 'Yes'),
            ('Sweet Pirate Chuches', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Tabetai España (Crepes)', 'Madrid', 'Indoor', 7, 'Yes', 'Yes'),
            ('Takomama', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Teleférico', 'Madrid', 'Indoor', 5, 'No', 'No'),
            ('Telescopio De Herschel', 'Madrid', 'Indoor', 4, 'No', 'No'),
            ('Templo De Debod', 'Madrid', 'Outdoor', 0, 'No', 'Yes'),
            ('Tenis Talavera', 'Talavera', 'Outdoor', 2.20, 'No', 'Yes'),
            ('Terraza Cr7', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Terraza Salvador Bachiller', 'Madrid', 'Indoor', 5, 'Yes', 'No'),
            ('Tienda Cerámica Talavera', 'Talavera', 'Indoor', 0, 'No', 'Yes'),
            ('Tienda Haribo Nassica', 'Madrid', 'Indoor', 3, 'Yes', 'No'),
            ('Tienda Reino de Juguetes Xmadrid', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Tiendas De Souvenirs Sol', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Tierra Burrito', 'Madrid', 'Indoor', 8, 'Yes', 'Yes'),
            ('Tiki Tako Clavel Gran Vía', 'Madrid', 'Indoor', 5, 'Yes', 'Yes'),
            ('Toledo', 'Talavera', 'Outdoor', 0, 'No', 'No'),
            ('Torre Moncloa', 'Madrid', 'Indoor', 4, 'No', 'No'),
            ('Tour Gratis Kaicao Madrid (Chocolate)', 'Madrid', 'Indoor', 0, 'Yes', 'No'),
            ('Tour Santiago Bernabeu', 'Madrid', 'Indoor', 28, 'No', 'No'),
            ('Tren Histórico De Arganda', 'Madrid', 'Outdoor', 7, 'No', 'No'),
            ('Trineo Navacerrada', 'Madrid', 'Outdoor', 0, 'No', 'No'),
            ('Turrón Donut Vicens Vives', 'Madrid', 'Indoor', 2, 'Yes', 'No'),
            ('Véneta', 'Madrid', 'Indoor', 3.5, 'Yes', 'Yes'),
            ('Ver Final Nadal Federer 2008', 'Madrid', 'Indoor', 0, 'No', 'No'),
            ('Virtuastation (Parque De Vr)', 'Madrid', 'Indoor', 5, 'No', 'No'),
            ('Visita Palacio Real', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Warner', 'Madrid', 'Outdoor', 29.90, 'No', 'No'),
            ('Warner Beach', 'Madrid', 'Outdoor', 19.90, 'No', 'Yes'),
            ('Xanadu', 'Madrid', 'Indoor', 0, 'No', 'Yes'),
            ('Yucatan X Godzilla', 'Madrid', 'Indoor', 10, 'Yes', 'Yes')`
          );
        }
      });

      tx.executeSql("SELECT COUNT(*) AS count FROM movies", [], (_, { rows }) => {
        if (rows.item(0).count === 0) { // insert if table is empty
          tx.executeSql(
            `INSERT INTO movies (title, type, duration, genre, platform, status) VALUES 
            ('10 Reasons Why I Hate You', 'Movie', '1h 37m', 'Drama', 'Disney+', 'Not watched'),
            ('21 Jump Street', 'Movie', '1h 50m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('50 Sombras de Grey', 'Saga', '6h', 'Drama', 'Netflix', 'Watched'),
            ('8 Apellidos Marroquíes', 'Movie', '1h 40m', 'Comedy', 'Netflix', 'Not watched'),
            ('A Quiet Place Day One', 'Movie', '1h 39m', 'Thriller', 'None', 'Not watched'),
            ('Acero Puro', 'Movie', '2h 7m', 'Sci-Fi', 'Netflix, Prime', 'Watched'),
            ('After', 'Saga', '9h', 'Drama', 'Prime', 'Watched'),
            ('Ahsoka', 'Series', '8 ep', 'Action', 'Disney+', 'Watched'),
            ('AI: Artificial Intelligence', 'Movie', '2h 26m', 'Sci-Fi', 'Max, Prime', 'Not watched'),
            ('Alicia En El País De Las Maravillas 1 y 2', 'Movie', '3h', 'Fantasy', 'Disney+', 'Watched'),
            ('Alien', 'Movie', '1h 57m', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Alien 2', 'Movie', '2h 17m', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Alien 3', 'Movie', '1h 54m', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Alien 4', 'Movie', '1h 49m', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Alien Romulus', 'Movie', '1h 59m', 'Sci-Fi', 'None', 'Watched'),
            ('Anarchy: La Noche De Las Bestias', 'Movie', '1h 43m', 'Horror', 'Netflix', 'Not watched'),
            ('Animales Fantásticos y Dónde Encontrarlos', 'Movie', '2h 12m', 'Fantasy', 'Prime', 'Not watched'),
            ('Animales Fantásticos y Dónde Encontrarlos 2', 'Movie', '2h 14m', 'Fantasy', 'Prime', 'Not watched'),
            ('Animales Fantásticos y Dónde Encontrarlos 3', 'Movie', '2h 22m', 'Fantasy', 'Prime', 'Not watched'),
            ('Anne With An E', 'Series', '27 ep', 'Drama', 'Netflix', 'Not watched'),
            ('Arcane', 'Series', '18 ep', 'Animation', 'Netflix', 'Watched'),
            ('Arthur', 'Movie', '1h 48m', 'Drama', 'None', 'Watched'),
            ('Baby Driver', 'Movie', '1h 53m', 'Action', 'Netflix', 'Watched'),
            ('Babylon', 'Movie', '3h 9m', 'Comedy, Drama', 'Prime', 'Not watched'),
            ('Bad Boys 1, 2 y 3', 'Saga', '6h', 'Action', 'Netflix', 'Watched'),
            ('Bad Boys Ride Or Die', 'Movie', '1h 55m', 'Action', 'None', 'Watched'),
            ('Ballerina', 'Movie', '0h', 'Action', 'None', 'Not watched'),
            ('Band of Brothers', 'Series', '10 ep', 'Action', 'Max', 'Not watched'),
            ('Barbie', 'Movie', '1h 54m', 'Comedy', 'Max, Prime', 'Watched'),
            ('Battleship', 'Movie', '2h 11m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Birdbox', 'Movie', '2h 4m', 'Thriller', 'Netflix', 'Watched'),
            ('Blade Runner', 'Movie', '1h 57m', 'Sci-Fi', 'Max, Prime', 'Not watched'),
            ('Break Point', 'Series', '10 ep', 'Documentary', 'Netflix', 'Watched'),
            ('Breaking Bad', 'Series', '62 ep', 'Thriller', 'Netflix', 'Not watched'),
            ('Bullet Train', 'Movie', '2h 7m', 'Action', 'Netflix, Prime', 'Watched'),
            ('Bumblebee', 'Movie', '1h 54m', 'Action', 'Prime', 'Watched'),
            ('Campeonex', 'Movie', '1h 47m', 'Comedy', 'Max', 'Watched'),
            ('Carrie', 'Movie', '1h 38m', 'Drama', 'Prime', 'Not watched'),
            ('Cars On The Road  (Ka-Chow)', 'Series', '9 ep', 'Animation', 'Disney+', 'Not watched'),
            ('Cazafantasmas: Imperio Helado', 'Movie', '1h 55m', 'Comedy', 'None', 'Not watched'),
            ('Cementerio De Animales', 'Movie', '1h 43m', 'Horror', 'Prime', 'Not watched'),
            ('Charlie y La Fábrica de Chocolate', 'Movie', '1h 55m', 'Fantasy', 'Netflix', 'Not watched'),
            ('Coco', 'Movie', '1h 45m', 'Animation', 'Disney+', 'Not watched'),
            ('Community', 'Series', '110 ep', 'Comedy', 'Prime, Disney+', 'Not watched'),
            ('Cómo Entrenar A Tu Dragon', 'Saga', '4h', 'Animation', 'Netflix, Prime', 'Not watched'),
            ('Crazy Rich Asians', 'Movie', '2h', 'Comedy', 'Netflix', 'Watched'),
            ('Crepúsculo Saga', 'Saga', '2h 2m', 'Drama', 'Netflix, Prime', 'Watched'),
            ('Cruella', 'Movie', '2h 14m', 'Drama', 'Disney+', 'Watched'),
            ('Cry Macho', 'Movie', '1h 44m', 'Drama', 'Max, Prime', 'Not watched'),
            ('Dark', 'Series', '26 ep', 'Sci-Fi', 'Netflix', 'Not watched'),
            ('Deadpool y Lobezno', 'Movie', '2h 7m', 'Action', 'Disney+', 'Watched'),
            ('Detective Pikachu', 'Movie', '1h 44m', 'Animation', 'Netflix', 'Not watched'),
            ('Doctor Strange : Multiverse Of Madness', 'Movie', '2h 6m', 'Action', 'Disney+', 'Watched'),
            ('Doctor Sueño', 'Movie', '2h 32m', 'Drama', 'Netflix, Prime', 'Not watched'),
            ('Documental Roger Federer', 'Movie', '1h 28m', 'Biography', 'Prime', 'Watched'),
            ('Dos Rubias De Pelo En Pecho', 'Movie', '1h 49m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Eduardo Manostijeras', 'Movie', '1h 45m', 'Drama', 'Disney+', 'Not watched'),
            ('El Aviador', 'Movie', '2h 50m', 'Biography', 'Prime', 'Not watched'),
            ('El Becario', 'Movie', '2h 1m', 'Drama', 'Netflix', 'Watched'),
            ('El Código Enigma', 'Movie', '1h 53m', 'Biography', 'Netflix, Prime', 'Not watched'),
            ('El Dictador', 'Movie', '1h 23m', 'Comedy', 'Netflix', 'Watched'),
            ('El Gato Con Botas', 'Movie', '1h 42m', 'Animation', 'Netflix', 'Watched'),
            ('El Juego De Ender', 'Movie', '1h 54m', 'Action', 'Netflix, Prime', 'Watched'),
            ('El Llanero Solitario', 'Movie', '2h 29m', 'Action', 'Disney+', 'Watched'),
            ('El Niño Del Pijama De Rayas', 'Movie', '1h 34m', 'Drama', 'Netflix, Prime', 'Not watched'),
            ('El Padrino 1, 2 y 3', 'Saga', '8h', 'Action', 'Prime', 'Not watched'),
            ('El Pingüino', 'Series', '8 ep', 'Action', 'Max', 'Watched'),
            ('El Planeta De Los Simios', 'Saga', '7h', 'Sci-Fi', 'Disney+', 'Watched'),
            ('El Reino Del Planeta De Los Simios', 'Movie', '2h 25m', 'Action', 'Disney+', 'Not watched'),
            ('El Resplandor', 'Movie', '2h 26m', 'Thriller', 'Max', 'Not watched'),
            ('Elemental', 'Movie', '1h 49m', 'Animation', 'Disney+', 'Watched'),
            ('Elvis', 'Movie', '2h 39m', 'Drama', 'Max, Prime', 'Watched'),
            ('Encanto', 'Movie', '1h 49m', 'Animation', 'Disney+', 'Watched'),
            ('Erase Una Vez En Hollywood', 'Movie', '2h 40m', 'Action', 'Netflix, Prime', 'Watched'),
            ('Escape Room', 'Movie', '1h 40m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Escape Room 2', 'Movie', '1h 28m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Extracción', 'Movie', '1h 56m', 'Action', 'Netflix', 'Not watched'),
            ('Extracción 2', 'Movie', '2h 3m', 'Action', 'Netflix', 'Not watched'),
            ('Fast And Furious Saga', 'Saga', '20h', 'Action', 'Prime', 'Watched'),
            ('Fear Street 1, 2 y 3', 'Saga', '5h', 'Thriller', 'Netflix', 'Watched'),
            ('Fiebre Del Sabado Noche', 'Movie', '1h 58m', 'Drama', 'Prime', 'Not watched'),
            ('Fly Me To The Moon', 'Movie', '2h 11m', 'Comedy', 'None', 'Not watched'),
            ('Ford V Ferrari', 'Movie', '2h 32m', 'Biography', 'Disney+', 'Not watched'),
            ('Forrest Gump', 'Movie', '2h 22m', 'Drama', 'Netflix', 'Watched'),
            ('Freedom Writers', 'Movie', '2h 3m', 'Drama', 'Netflix, Prime', 'Watched'),
            ('Friends', 'Series', '236 ep', 'Comedy', 'Netflix, Prime', 'Not watched'),
            ('Furia De Titanes', 'Movie', '1h 46m', 'Action', 'Prime', 'Watched'),
            ('Gambito De Dama', 'Series', '7 ep', 'Drama', 'Netflix, Max, Prime', 'Watched'),
            ('Gifted', 'Movie', '1h 41m', 'Drama', 'Disney+', 'Not watched'),
            ('Godzilla y Kong: El Nuevo Imperio', 'Movie', '1h 55m', 'Action', 'Max, Prime', 'Not watched'),
            ('Gran Torino', 'Movie', '1h 56m', 'Drama', 'Netflix, Prime', 'Not watched'),
            ('Gran Turismo', 'Movie', '2h 15m', 'Action', 'Prime', 'Not watched'),
            ('Gravity', 'Movie', '1h 31m', 'Sci-Fi', 'Max', 'Not watched'),
            ('Grease', 'Movie', '1h 45m', 'Musical', 'Prime', 'Watched'),
            ('Greyhound', 'Movie', '1h 31m', 'Action', 'None', 'Not watched'),
            ('Grown Ups', 'Movie', '1h 41m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Grown Ups 2', 'Movie', '1h 42m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Gru 4', 'Movie', '1h 34m', 'Animation', 'None', 'Watched'),
            ('Guardiana De Dragones', 'Movie', '1h 40m', 'Animation', 'None', 'Not watched'),
            ('Guardianes De La Galaxia 1, 2 y 3', 'Saga', '5h', 'Action', 'Disney+', 'Watched'),
            ('Hachiko', 'Movie', '1h 33m', 'Drama', 'Prime', 'Not watched'),
            ('Happy Gilmore', 'Movie', '1h 32m', 'Comedy', 'Netflix, Prime', 'Not watched'),
            ('Harry Potter', 'Saga', '20h', 'Fantasy', 'Max, Prime', 'Watched'),
            ('Hidden Figures', 'Movie', '2h 7m', 'Biography', 'Disney+', 'Watched'),
            ('Hobbit', 'Saga', '8h', 'Fantasy', 'Prime', 'Watched'),
            ('I Wanna Dance With Somebody', 'Movie', '2h 24m', 'Biography', 'Netflix, Prime', 'Not watched'),
            ('Indiana Jones', 'Movie', '10h', 'Action', 'Disney+', 'Watched'),
            ('Indiana Jones y El Dial Del Destino', 'Movie', '2h 34m', 'Action', 'Disney+', 'Watched'),
            ('Inside Out', 'Movie', '1h 35m', 'Animation', 'Disney+', 'Watched'),
            ('Inside Out 2', 'Movie', '1h 36m', 'Animation', 'Disney+', 'Watched'),
            ('Ira De Titanes', 'Movie', '1h 39m', 'Action', 'Prime', 'Not watched'),
            ('Isnt It Romantic?', 'Movie', '1h 29m', 'Comedy', 'Netflix', 'Watched'),
            ('John Wick 1, 2, 3 y 4', 'Saga', '9h', 'Action', 'Prime', 'Watched'),
            ('Joker 2', 'Movie', '2h 18m', 'Action', 'Disney+', 'Watched'),
            ('Juego De Armas', 'Movie', '1h 54m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Jungle Cruise', 'Movie', '2h 7m', 'Action', 'Disney+', 'Not watched'),
            ('Jurassic Park', 'Saga', '7h 30m', 'Sci-Fi', 'Max, Prime', 'Watched'),
            ('Jurassic World', 'Saga', '7h 30m', 'Sci-Fi', 'Prime', 'Watched'),
            ('King Richard', 'Movie', '2h 24m', 'Biography', 'Max, Prime', 'Watched'),
            ('Kung Fu Panda 4', 'Movie', '1h 30m', 'Animation', 'Netflix, Prime', 'Watched'),
            ('La Bella y La Bestia (Emma Watson)', 'Movie', '2h 9m', 'Musical', 'Disney+', 'Not watched'),
            ('La Cita De Carl', 'Movie', '7m', 'Animation', 'Disney+', 'Watched'),
            ('La La Land', 'Movie', '2h 8m', 'Musical', 'Prime', 'Not watched'),
            ('La Novia Cadaver', 'Movie', '1h 17m', 'Animation', 'Max, Prime', 'Watched'),
            ('La Sirenita', 'Movie', '2h 15m', 'Musical', 'Disney+', 'Watched'),
            ('Las Crónicas De Narnia 1-4', 'Saga', '10h', 'Adventure', 'Disney+', 'Not watched'),
            ('Las Ventajas De Ser Un Marginado', 'Movie', '1h 43m', 'Drama', 'Netflix, Prime', 'Watched'),
            ('Legally Blonde', 'Movie', '1h 36m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Lift', 'Movie', '1h 39m', 'Comedy', 'Netflix', 'Not watched'),
            ('Lightyear', 'Movie', '1h 45m', 'Animation', 'Disney+', 'Watched'),
            ('Lilo & Stitch', 'Movie', '1h 25m', 'Animation', 'Disney+', 'Watched'),
            ('Lilo & Stitch 2', 'Movie', '1h 8m', 'Animation', 'Disney+', 'Watched'),
            ('Lobezno y Logan', 'Saga', '5h', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Locke & Key', 'Series', '28 ep', 'Fantasy', 'Netflix', 'Watched'),
            ('Loki', 'Series', '12 ep', 'Action', 'Disney+', 'Watched'),
            ('Lord Of The Rings', 'Saga', '12h', 'Fantasy', 'Prime', 'Watched'),
            ('Los Becarios', 'Movie', '1h 59m', 'Comedy', 'Disney+', 'Watched'),
            ('Los Croods', 'Movie', '1h 38m', 'Animation', 'Netflix, Prime', 'Watched'),
            ('Los Croods 2', 'Movie', '1h 35m', 'Animation', 'Netflix, Prime', 'Watched'),
            ('Los Increibles 3', 'Movie', '0h', 'Animation', 'Disney+', 'Not watched'),
            ('Los Juegos Del Hambre: Balada De Pájaros Cantores y Serpientes', 'Movie', '2h 37m', 'Action', 'Prime', 'Watched'),
            ('LOTR: Rings Of Power', 'Series', '16 ep', 'Fantasy', 'Prime', 'Watched'),
            ('Luca', 'Movie', '1h 35m', 'Animation', 'Disney+', 'Watched'),
            ('Magic Mike', 'Movie', '1h 50m', 'Comedy', 'Prime', 'Not watched'),
            ('Malditos Bastardos', 'Movie', '2h 33m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Mamma Mia', 'Movie', '1h 48m', 'Musical', 'Netflix, Prime', 'Not watched'),
            ('Mamma Mia 2', 'Movie', '1h 54m', 'Musical', 'Netflix, Prime', 'Not watched'),
            ('Mean Girls', 'Movie', '1h 37m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Megalodon 2', 'Movie', '1h 56m', 'Action', 'Max, Prime', 'Watched'),
            ('Memorias De Un Asesino Internacional', 'Movie', '1h 37m', 'Comedy', 'Prime', 'Watched'),
            ('Men In Black', 'Saga', '1h 38m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Mientras Dure La Guerra', 'Movie', '1h 47m', 'Drama', 'Netflix, Prime', 'Not watched'),
            ('Million Dollar Baby', 'Movie', '2h 12m', 'Drama', 'Prime', 'Not watched'),
            ('Minions', 'Saga', '1h 31m', 'Animation', 'Netflix', 'Watched'),
            ('Minions: The Rise Of Gru', 'Movie', '1h 27m', 'Animation', 'Netflix', 'Watched'),
            ('Misery', 'Movie', '1h 47m', 'Drama', 'Prime', 'Watched'),
            ('Moana 2', 'Movie', '1h 40m', 'Animation', 'Disney+', 'Watched'),
            ('Moana 2 (V.O.)', 'Movie', '1h 40m', 'Animation', 'Disney+', 'Not watched'),
            ('Modern Family', 'Series', '250 ep', 'Comedy', 'Disney+', 'Not watched'),
            ('Nacho Libre', 'Movie', '1h 32m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Napoleón', 'Movie', '2h 30m', 'Biography', 'None', 'Not watched'),
            ('Ninja Turtles: Caos Mutante', 'Movie', '1h 39m', 'Animation', 'Netflix', 'Not watched'),
            ('Noche En El Museo Trilogía', 'Saga', '6h', 'Comedy', 'Disney+', 'Watched'),
            ('Obi-Wan', 'Series', '6 ep', 'Action', 'Disney+', 'Watched'),
            ('Oppenheimer', 'Movie', '3h', 'Biography', 'Prime', 'Watched'),
            ('Ordinary World', 'Movie', '1h 27m', 'Comedy, Drama', 'Prime', 'Not watched'),
            ('Origen', 'Movie', '2h 28m', 'Sci-Fi', 'Netflix, Prime', 'Watched'),
            ('Pacific Rim', 'Movie', '2h 11m', 'Action', 'Netflix, Prime', 'Watched'),
            ('Pasando Bolas Rafa Nadal', 'Movie', '1h 10m', 'Biography', 'Max', 'Not watched'),
            ('Percy Jackson y Los Dioses Del Olimpo', 'Series', '8 ep', 'Adventure', 'Disney+', 'Watched'),
            ('Pesadilla Antes De Navidad', 'Movie', '1h 16m', 'Animation', 'Disney+', 'Not watched'),
            ('Piratas Del Caribe', 'Saga', '10h', 'Action', 'Disney+', 'Not watched'),
            ('Pobres Criaturas', 'Movie', '2h 21m', 'Drama', 'Prime', 'Not watched'),
            ('Polar Express', 'Movie', '1h 40m', 'Animation', 'Prime', 'Not watched'),
            ('Pretty Woman', 'Movie', '1h 59m', 'Comedy', 'Disney+', 'Not watched'),
            ('Pulp Fiction', 'Movie', '2h 34m', 'Action', 'Prime', 'Not watched'),
            ('Quantumania', 'Movie', '2h 5m', 'Sci-Fi', 'Disney+', 'Watched'),
            ('Rebel Moon', 'Movie', '2h 15m', 'Action', 'Netflix', 'Not watched'),
            ('Rogue One', 'Movie', '2h 13m', 'Action', 'Disney+', 'Watched'),
            ('Rush', 'Movie', '2h 3m', 'Action', 'Prime', 'Watched'),
            ('Rush Hour', 'Saga', '3h', 'Action', 'Netflix, Prime', 'Watched'),
            ('Salems Lot', 'Movie', '1h 52m', 'Thriller', 'Prime', 'Not watched'),
            ('School Of Rock', 'Movie', '1h 48m', 'Comedy', 'None', 'Not watched'),
            ('Serpientes En El Avión', 'Movie', '1h 45m', 'Action', 'Netflix', 'Not watched'),
            ('Sex Education Season 4', 'Series', '8 ep', 'Drama', 'Netflix', 'Not watched'),
            ('Skeleton Crew', 'Series', '8 ep', 'Sci-Fi', 'Disney+', 'Not watched'),
            ('Solo', 'Movie', '2h 15m', 'Action', 'Disney+', 'Watched'),
            ('Sonic', 'Movie', '1h 39m', 'Animation', 'Prime', 'Watched'),
            ('Sonic 2', 'Movie', '2h 2m', 'Animation', 'Prime', 'Watched'),
            ('Sonic 3', 'Movie', '1h 50m', 'Animation', 'Prime', 'Watched'),
            ('Soy Leyenda', 'Movie', '1h 41m', 'Sci-Fi', 'Max, Prime', 'Not watched'),
            ('Spiderman Cruzando El Multiverso', 'Saga', '6h', 'Animation', 'Netflix', 'Not watched'),
            ('Spirited', 'Movie', '2h 7m', 'Comedy', 'None', 'Watched'),
            ('Squid Game Season 2', 'Series', '8 ep', 'Thriller', 'Netflix', 'Watched'),
            ('Star Wars', 'Saga', '25h', 'Sci-Fi', 'Netflix, Prime', 'Watched'),
            ('Stranger Things', 'Series', '34 ep', 'Sci-Fi', 'Netflix', 'Watched'),
            ('Suegros De Armas Tomar', 'Movie', '1h 35m', 'Comedy', 'Netflix', 'Not watched'),
            ('Sully', 'Movie', '1h 36m', 'Drama', 'None', 'Not watched'),
            ('Super Mario Bros Movie', 'Movie', '1h 32m', 'Animation', 'Prime', 'Watched'),
            ('Superbad', 'Movie', '1h 59m', 'Comedy', 'Netflix', 'Watched'),
            ('Sweeny Todd', 'Movie', '1h 56m', 'Musical', 'Max, Prime', 'Not watched'),
            ('Tales Of The Empire', 'Series', '6 ep', 'Animation', 'Disney+', 'Watched'),
            ('Tales Of The Jedi', 'Series', '6 ep', 'Animation', 'Disney+', 'Watched'),
            ('Taylor Swift: The Eras Tour', 'Movie', '2h 48m', 'Biography', 'Disney+', 'Watched'),
            ('Terminator', 'Movie', '1h 47m', 'Action', 'Prime', 'Not watched'),
            ('The Acolyte', 'Series', '8 ep', 'Sci-Fi', 'Disney+', 'Watched'),
            ('The Artful Dodger', 'Series', '8 ep', 'Drama', 'Disney+', 'Watched'),
            ('The Bad Batch (Star Wars)', 'Series', '16 ep', 'Animation', 'Disney+', 'Not watched'),
            ('The Batman', 'Movie', '2h 56m', 'Action', 'Netflix, Max, Prime', 'Watched'),
            ('The Book Of Boba Fett', 'Series', '7 ep', 'Action', 'Disney+', 'Watched'),
            ('The Boy The Mole The Fox And The Horse', 'Movie', '34m', 'Animation', 'None', 'Watched'),
            ('The Boys', 'Series', '32 ep', 'Action', 'Prime', 'Watched'),
            ('The Clone Wars', 'Series', '133 ep', 'Action', 'Disney+', 'Not watched'),
            ('The Fablemans', 'Movie', '2h 31m', 'Biography', 'Prime', 'Watched'),
            ('The Great Gatsby (Leo Dicaprio)', 'Movie', '2h 23m', 'Drama', 'Prime', 'Not watched'),
            ('The Hustle', 'Movie', '1h 34m', 'Comedy', 'Prime', 'Not watched'),
            ('The Interview', 'Movie', '1h 52m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('The Mandalorian', 'Series', '24 ep', 'Action', 'Disney+', 'Watched'),
            ('The Mandalorian & Grogu', 'Movie', '0h', 'Action', 'Disney+', 'Not watched'),
            ('The Menu', 'Movie', '1h 46m', 'Thriller', 'Disney+', 'Watched'),
            ('The Night Of', 'Series', '8 ep', 'Drama', 'Max', 'Not watched'),
            ('The Outsider', 'Series', '10 ep', 'Thriller', 'Max', 'Not watched'),
            ('The Pacific', 'Series', '10 ep', 'Action', 'Max', 'Not watched'),
            ('The Willoughbys', 'Movie', '1h 30m', 'Animation', 'Netflix', 'Not watched'),
            ('This Is The End', 'Movie', '1h 47m', 'Comedy', 'Netflix', 'Watched'),
            ('Thor: Love And Thunder', 'Movie', '1h 59m', 'Action', 'Disney+', 'Watched'),
            ('Tiana y El Sapo', 'Movie', '1h 37m', 'Animation', 'Disney+', 'Watched'),
            ('Tick Tick Boom', 'Movie', '1h 55m', 'Musical', 'Netflix', 'Watched'),
            ('Top Gun', 'Movie', '1h 49m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Top Gun 2', 'Movie', '2h 11m', 'Action', 'Netflix, Prime', 'Not watched'),
            ('Transformers Saga', 'Saga', '15h', 'Action', 'Prime', 'Not watched'),
            ('Trilogía Batman', 'Saga', '5h', 'Action', 'Max, Prime', 'Watched'),
            ('Trilogía Divergente', 'Saga', '6h', 'Action', 'Netflix, Prime', 'Watched'),
            ('Trilogía El Corredor Del Laberinto', 'Saga', '6h', 'Action', 'Prime', 'Watched'),
            ('Trilogía El Planeta De Los Simios', 'Saga', '6h', 'Action', 'Disney+', 'Watched'),
            ('Trilogía Los Juegos Del Hambre', 'Saga', '6h', 'Action', 'Prime', 'Watched'),
            ('Tron Legacy', 'Movie', '2h 5m', 'Action', 'Disney+', 'Not watched'),
            ('Una Pareja De 3', 'Movie', '1h 55m', 'Comedy', 'Disney+', 'Watched'),
            ('Up', 'Movie', '1h 36m', 'Animation', 'Disney+', 'Not watched'),
            ('Vaiana', 'Movie', '1h 47m', 'Animation', 'Disney+', 'Watched'),
            ('Venom: The Last Dance', 'Movie', '1h 50m', 'Action', 'None', 'Watched'),
            ('Wall E', 'Movie', '1h 38m', 'Animation', 'Disney+', 'Watched'),
            ('Watchmen', 'Series', '9 ep', 'Action', 'Max', 'Not watched'),
            ('Westside Story', 'Movie', '2h 36m', 'Musical', 'Disney+', 'Not watched'),
            ('Why Him', 'Movie', '1h 51m', 'Comedy', 'Netflix, Prime', 'Watched'),
            ('Wish', 'Movie', '1h 30m', 'Animation', 'Disney+', 'Watched'),
            ('Wonder', 'Movie', '1h 53m', 'Drama', 'Netflix, Prime', 'Not watched'),
            ('Wonka', 'Movie', '1h 56m', 'Musical', 'Max, Prime', 'Watched')`
          );
        }
      });
    });

    setDbLoaded(true);
  },[])

  const [fontsLoaded] = useFonts({
    'Montserrat-Regular': require('./assets/fonts/Montserrat-Regular.ttf'),
    'Montserrat-Bold': require('./assets/fonts/Montserrat-Bold.ttf'),
    'Montserrat-Medium': require('./assets/fonts/Montserrat-Medium.ttf'),
    'Montserrat-SemiBold': require('./assets/fonts/Montserrat-SemiBold.ttf'),
  });

  if (!fontsLoaded || !dbLoaded) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" />
        <Text style={{fontSize: 26, fontWeight: 'bold'}}>Loading Database...</Text>
      </View>
    );
  } else {
    SplashScreen.hideAsync(); // Hide splash screen
  }

  return (
    <NavigationContainer>
      <Suspense fallback={
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <ActivityIndicator size="large" />
            <Text style={{fontSize: 26, fontWeight: 'bold'}}>Loading Database...</Text>
          </View>}
        >
        <SQLiteProvider databaseName='chispas.db' useSuspense>
          <Stack.Navigator>
            <Stack.Screen name="Home" component={Home} options={{headerShown: false}}/>
            <Stack.Screen name="Movies" component={Movies} options={{headerShown: false}}/>
            <Stack.Screen name="Plans" component={Plans} options={{headerShown: false}}/>
            <Stack.Screen name="NewMovie" component={NewMovie} options={{headerShown: false}}/>
            <Stack.Screen name="NewPlan" component={NewPlan} options={{headerShown: false}}/>
            <Stack.Screen name="EditMovie" component={EditMovie} options={{headerShown: false}}/>
            <Stack.Screen name="EditPlan" component={EditPlan} options={{headerShown: false}}/>
          </Stack.Navigator>
        </SQLiteProvider>
      </Suspense>
    </NavigationContainer>
  );
}
